### mass creation
POST http://localhost:8080/api/StorageService/massCreate HTTP/1.1
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
    "row" :3,
    "rowType" : "C",
    "col" : 4,
    "colType" : "N",
    "storage" : "92A5F984-7C3B-4A36-9883-4F7EDBA1D9F3"
}

### Get storage slot
GET http://localhost:8080/api/StorageService/StorageSlot
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=


### Get storage slot
GET http://localhost:8080/api/StorageService/
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Get storage
GET http://localhost:8080/api/StorageService/Storage
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Get slot status
GET http://localhost:8080/api/StorageService/SlotStatus
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Insert new storage
POST http://localhost:8080/api/StorageService/Storage HTTP/1.1
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
    "name" : "S200",
    "buildingFloor" : "7D5A658D-D9C1-44E6-9DA0-1D29069C4617"
}

# GET http://localhost:8080/odata/v4/StorageService/Storage
# Content-Type: application/json
# Authorization: Basic authenticated:
