### mass creation
POST http://localhost:8084/api/StorageService/massCreate HTTP/1.1
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
    "row" :3,
    "rowType" : "C",
    "col" : 4,
    "colType" : "N",
    "storage" : "92A5F984-7C3B-4A36-9883-4F7EDBA1D9F3"
}

### Get storage slot
GET http://localhost:8084/api/StorageService/StorageSlot
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Get building floor
GET http://localhost:8084/api/StorageService/BuildingFloor
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Get storage slot
GET http://localhost:8084/api/StorageService/
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Get storages
GET http://localhost:8080/api/StorageService/Storage
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=


### Get specific storage
GET http://localhost:8080/api/StorageService/Storage(ID=92a5f984-7c3b-4a36-9883-4f7edba1d9f3,IsActiveEntity=true)
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Get slot status
GET http://localhost:8080/api/StorageService/SlotStatus
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Insert new storage
POST http://localhost:8080/api/StorageService/Storage HTTP/1.1
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
    "name" : "S200",
    "locationInstructions": "Ghost place",
    "map": "https://longlegpenguin.githu.io",
    "buildingFloor" : "7D5A658D-D9C1-44E6-9DA0-1D29069C4617"
}

###
# GET http://localhost:8080/odata/v4/StorageService/Storage
# Content-Type: application/json
# Authorization: Basic authenticated:

### Delete a slot
DELETE http://localhost:8080/api/StorageService/StorageSlot(ID=94b5eef2-8ec5-4c2e-87e6-d78809f01c68,IsActiveEntity=true) HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=

### 
DELETE http://localhost:8080/api/StorageService/StorageSlot(ID=94b5eef2-8ec5-4c2e-87e6-d78809f01c68,IsActiveEntity=false) HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=

/Storage(ID=adf15060-9907-4ea3-be7e-db12a6277165,IsActiveEntity=true)/
### 
GET http://localhost:8084/api/StorageService/StorageSlot(ID=9be3cedc-e657-4a8b-b37e-ffc494d96952) HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=
### 
GET http://localhost:8084/api/StorageService/Storage(ID=adf15060-9907-4ea3-be7e-db12a6277165,IsActiveEntity=true)/storageSlot(ID=9be3cedc-e657-4a8b-b37e-ffc494d96952,IsActiveEntity=true) HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=

###
GET http://localhost:8084/api/StorageService/Storage(ID=adf15060-9907-4ea3-be7e-db12a6277165)/storageSlot(ID=94b5eef2-8ec5-4c2e-87e6-d78809f01c68) HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=


############### Delivery company tests

### Get all packages
GET http://localhost:8084/api/PackageService/Package HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=

### Get a package (deliver company = 6480a902-007c-4cdd-a6a3-0f3a88d24fe0)
GET http://localhost:8084/api/DummyService/Package(ID=07f88a8e-a23b-4305-8866-225038492304) HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=

### Get a package (deliver company = 6480a902-007c-4cdd-a6a3-0f3a88d24fe0)
GET http://localhost:8084/api/DummyService/Package HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=

### Get all delevery companies
GET http://localhost:8084/api/CompanyService/DeliveryCompany HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=
### Deletion of a company results relevant pavkages reference removed
DELETE http://localhost:8084/api/CompanyService/DeliveryCompany(ID=6480a902-007c-4cdd-a6a3-0f3a88d24fe0) HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=

############### Package service test
### Get all storage slots
GET http://localhost:8084/api/StorageService/StorageSlot HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=

### Get all packages
GET http://localhost:8084/api/PackageService/Package HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=

### Get a package (8fb3403b-1e14-43f5-9bb9-8b20113bb70a)
GET http://localhost:8084/api/PackageService/Package(ID=8fb3403b-1e14-43f5-9bb9-8b20113bb70a) HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=

### Get a storage slot -> it is empty, should be inuse after put in package
GET http://localhost:8084/api/StorageService/StorageSlot(ID=9be3cedc-e657-4a8b-b37e-ffc494d96952) HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=

### Call confirm action
POST http://localhost:8084/api/PackageService/confirm HTTP/1.1
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "packagesIds": ["b414b0fe-5645-418c-98c3-4a740bbd7bb5", "8fb3403b-1e14-43f5-9bb9-8b20113bb70a"],
  "slotId": "9be3cedc-e657-4a8b-b37e-ffc494d96952"
}