spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
  web.resources.static-locations: "file:./app/"
cds:
  data-source.auto-config.enabled: false
  data-source:
    csv:
      paths:
        - db/data
        - db/data/**
        - test/data
        - test/data/**
        - ../test/data/**
  sql.supportedLocales: "*"
  # odata-v4.endpoint.path: "/odata/v4"
  # odata-v2.endpoint.path: "/odata/v2"
  odata-v4.serializer.enabled: true
  multi-tenancy:
    compatibility.enabled: false
    mtxs.enabled: true
  security:
    authentication.normalize-provider-tenant: true
    mock.users:
      I123456:
        password: admin
        roles:
          - Administrator
          - User
      I111111:
        password: user
        roles:
          - User
      I234567:
        password: manager
        roles:
          - FacilityManager
      C456789:
        password: recep
        roles:
          - Receptionist
server:
  port: 8084

---
spring:
  config.activate.on-profile: test
  sql.init.schema-locations: classpath:schema-h2.sql
  web.resources.static-locations: "file:./app/"
cds:
  dataSource:
    autoConfig:
      enabled: false
    csv:
      paths:
        - test/data
        - test/data/**
        - ../test/data/**
        - db/data
        - db/data/**
        - ../db/data**
  odata-v4.endpoint.path: "/api"
  odata-v2.endpoint.path: "/api-v2"
  odata-v4.serializer.enabled: true
  multi-tenancy:
    compatibility.enabled: false
    mtxs.enabled: true
  security:
    authentication.normalize-provider-tenant: true
    mock.users:
      admin:
        password: admin
        roles:
          - Administrator
      I111111:
        password: user
        roles:
          - User
      manager:
        password: manager
        roles:
          - FacilityManager
      recep:
        password: recep
        roles:
          - Receptionist
      I333333:
        password: user
        roles:
          - User
