spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
  web.resources.static-locations: "file:./app/"
cds:
  data-source.auto-config.enabled: false
  data-source:
    csv:
      paths: test/data
  sql.supportedLocales: "*" ## cut
  odata-v4.endpoint.path: "/api"
  odata-v4.serializer.enabled: true
  multi-tenancy:
    compatibility.enabled: false
    mtxs.enabled: true
  security:
    authentication.normalize-provider-tenant: true
    mock.users:
      admin:
        password: admin
        roles:
        - Administrator
      user:
        password: user
      manager:
        password: manager
        roles:
        - FacilityManager
server:
  port: 8084